export enum ApiEndPoint {
    login = "api/User/PatientLogin",
    patientDetail = "api/User/GetPatientDetails",
    doctors = "api/Admin/GetDoctorList",
    consentForm="api/User/GetConsentForm",
    visitList = "api/User/GetAllVisits",
    LabReport  = "api/User/LabReport",
    RisReport = "api/User/RISReport",
    appointment = "api/User/GetPatitentAppointments",
    saveConsent = "api/User/SaveConsentForm",
    getAbout = "api/Admin/GetAbout",
    complaintList = "api/Admin/GetComplaints",
    messagesList = "api/Chat/chatUsers",
    complaintType = "api/Admin/GetComplaintTypes",
    addComplaint = "api/Admin/AddUpdateComplaint",
    chatHistory = "api/Chat/messages/history",
    sendMessage="api/Chat/sendMessage",
    complaintReply="api/Admin/GetComplaintReplys",
    addUpdatecomplaint="api/Admin/AddUpdateComplaintReply",
    DoctorTimeSlot = "api/User/GetDoctorTimeSlot",
    availableDates = "api/User/GetAvailableDates",
    bookAppointment = "api/User/CreateAppointment",
    medication = "api/User/GetAllMedications",
    requestType = "api/User/GetAllRequestTypes",
    requestList = "api/User/GetAllRequests",
    healthTracker ="api/User/GetHealthRecordsByType",
    addBloodPressure ="api/User/AddOrUpdateBloodPressureRecord",
    addBloodSugar ="api/User/AddOrUpdateBloodSugarRecord",
    addHeartRate ="api/User/AddOrUpdateHeartRateRecord",
    addWeight ="api/User/AddOrUpdateWeightRecord",
    addStep ="api/User/AddOrUpdateStepRecord",
    educationalMaterial = "api/User/GetEducationMaterials",
    educationalStatus = "api/User/UpdateEducationMaterialStatus",
    addRequest ="api/User/AddOrUpdateRequest"
}

