export enum ApiEndPoint {
    login = "api/User/PatientLogin",
    patientDetail = "api/User/GetPatientDetails",
    doctors = "api/Admin/GetDoctorList",
    consentForm = "api/User/GetConsentForm",
    visitList = "api/User/GetAllVisits",
    LabReport = "api/User/LabReport",
    RisReport = "api/User/RISReport",
    appointment = "api/User/GetPatitentAppointments",
    saveConsent = "api/User/SaveConsentForm",
    getAbout = "api/Admin/GetAbout",
    complaintList = "api/Admin/GetComplaints",
    messagesList = "api/Chat/chatUsers",
    complaintType = "api/Admin/GetComplaintTypes",
    addComplaint = "api/Admin/AddUpdateComplaint",
    chatHistory = "api/Chat/messages/history",
    sendMessage = "api/Chat/sendMessage",
    complaintReply = "api/Admin/GetComplaintReplys",
    addUpdatecomplaint = "api/Admin/AddUpdateComplaintReply",
    DoctorTimeSlot = "api/User/GetDoctorTimeSlot",
    availableDates = "api/User/GetAvailableDates",
    bookAppointment = "api/User/CreateAppointment",
    medication = "api/User/GetAllMedications",
    requestType = "api/User/GetAllRequestTypes",
    requestList = "api/User/GetAllRequests",
    healthTracker = "api/User/GetHealthRecordsByType",
    xray = "api/User/GetXrayReports",
    addBloodPressure = "api/User/AddOrUpdateBloodPressureRecord",
    addBloodSugar = "api/User/AddOrUpdateBloodSugarRecord",
    addHeartRate = "api/User/AddOrUpdateHeartRateRecord",
    addWeight = "api/User/AddOrUpdateWeightRecord",
    addStep = "api/User/AddOrUpdateStepRecord",
    educationalMaterial = "api/User/GetEducationMaterials",
    educationalStatus = "api/User/UpdateEducationMaterialStatus",
    addRequest = "api/User/AddOrUpdateRequest",
    educationalMaterialDetail = "api/User/GetEducationMaterialDetail",
    cancelAppointment = "api/User/CancelAppointment",
    rescheduleAppointment = "api/User/RescheduleAppointment",
    satisfactionList = "api/User/GetPatientSatisfactionList",
    addUpdateSatisfaction = "api/User/AddOrUpdatePatientSatisfaction",
    satisfactionDetail = "api/User/GetPatientSatisfactionDetail",
    sendPhoneOtp = "api/User/SendPhoneOtp",
    verifyPhone = "api/User/VerifyPhone",
    requestDetail = "api/User/GetRequestDetail",
    patientAssign = "api/User/AssignMaterialToPatient",
    healthImage = "api/User/UploadVitalPicture",
    patientReport = "api/User/GetPatientReport",

    // Doctor Login

    doctorLogin = "api/User/DoctorLogin",
    doctorAppointment = "api/User/GetDoctorAppointments",
    doctorPatient = "api/Admin/GetPatientList",
    doctorMedication = "api/User/GetAllMedications",
    medicationStatus = "api/User/SetMedicationStatus",
    doctorVisit = "api/User/GetAllVisits",
    getterms = "api/Admin/GetTermsHtml",
    recordType = "api/User/GetHealthRecordsByType",
    doctorDetail = "api/User/GetDoctorDetails",
    addMedication = "api/User/AddOrUpdateMedication ",
    medicationDetail = "api/User/GetMedicationDetail",
    messageList = "api/Chat/chatUsers",
    addEducationMaterial = "api/User/AddOrUpdateEducationMaterial",
    vitalStatus = "api/User/SetVitalRecordStatus",
    visitDetail = "api/User/GetVisitDetail",
    onlineStatus = "api/Chat/updateOnlineStatusManually",
    visitupdation = "api/Admin/UpdateVisitSection",
    Notification = "api/Notification/getNotificationList",
    tockenFcm = 'api/Notification/updateFCMToken',
    xrayDetail = "api/User/GetXrayReportDetail",
    uploadXray = "api/User/UploadXrayReport",
    
}

